== Open Source on AWS

=== Getting started

Axxes accounts are managed through Active Directory.
In the top left corner in Office365, search for an application called **AWS SSO**.
A menu should show up with all available accounts, choose **traineeship-2022**.

In the top right corner in the AWS Console, there's a dropdown with available regions.
Choose **eu-west-1**.

In the top left corner, open **services** for an overview of available services in AWS.

To install the AWS CLI, use the instructions https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[here].

=== Setting up a server

=== Creating an EC2 instance

- Go to the **EC2** console
- Pick **launch instance**, it should be a bright orange button.
- Fill in the **Name** field, this will set the **name** tag on the server.
- Select an AMI, for this session, we will use **Amazon Linux 2 AMI (HVM), SSD Volume Type**
- Pick an instance type, it doesn't have to be big, **t2.micro** will work just fine
- Create a new key pair -> enter a unique name -> choose type **RSA** and format **.pem**
- Make sure a public IP will be assigned, this is enabled by default
- Add a security group with access to port **22** from **0.0.0.0/0**
- Launch the instance!

.Show CLI command to launch an instance
[%collapsible]
====
[source,shell]
----
$ aws ec2 run-instances --image-id ami-089950bc622d39ed8 --instance-type t2.micro --key-name rob --region eu-west-1
----
====

=== Connecting to the EC2 instance

There are multiple ways to connect to a running EC2 instance, but I prefer **ssh**.

[source, shell]
----
$ chmod 400 <key>.pem
$ ssh -i <key>.pem ec2-user@<public-ip>
----

=== Infrastructure as Code

CloudFormation is the AWS solution to do infrastructure as code. Instead of manually configuring resources,
you can define these in YAML or JSON format and apply these configurations in the CloudFormation console.

The configuration template for the EC2 instance we just set up, can be found in link:../snippets/cloudformation/ec2.yaml[ec2.yaml].

.Click to expand
[%collapsible]
====
[source, yaml]
----
include::../snippets/cloudformation/ec2.yaml[]
----
====

=== Ansible on AWS

=== AWS Elastic Beanstalk

=== DNS

=== Containers on AWS

=== S3

=== AWS Lambda
