name: Deploy

on: [push]

#on:
#  push:
#    branches:
#      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn build
        env:
          CI: true
      - name: Archive Next build
        uses: actions/upload-artifact@v2
        with:
          name: next-out
          path: out
  aws:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        working-directory: ./deploy/aws
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build CloudFormation
        working-directory: ./deploy/aws
        run: python templates/static_website.py
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: rob-kenis-dot-com
          template: deploy/aws/output/static_website.json
      - name: Download Next build
        uses: actions/download-artifact@v2
        with:
          name: next-out
      - uses: chrislennon/action-aws-cli@v1.1
      - name: Upload website
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name rob-kenis-dot-com | jq -r '.Stacks[].Outputs[] | select(.OutputKey=="WebsiteOriginBucketName") | .OutputValue')
          aws s3 sync out/ s3://$BUCKET_NAME/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  azure:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure
        run: echo 'Update Azure infrastructure'
