name: 'Validate'

on:
  push:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "deploy/aws/templates/"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=setup.cfg"
          isort-options: "-w 100"