name: Validate

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build NextJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn lint
        env:
          CI: true
